# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 21:13
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE SCHEMA "networktoken";
            """,
            """
            DROP SCHEMA "networktoken";
            """,
        ),
        (
            """
            CREATE OR REPLACE VIEW "networktoken"."guest" AS SELECT
                n.id AS id,
                'guest_' || n.id::varchar AS username,
                n.value AS password
            FROM
                "public"."networktoken_token" n
            WHERE n.created + n.lifetime > NOW();
            """,
            """
            DROP VIEW "networktoken"."guest";
            """,
        ),
        (
            """
            CREATE OR REPLACE VIEW "networktoken"."internal" AS SELECT
                row_number() over () AS id,
                co.BENUTZERNAME AS username,
                co.KENNWORT AS password,
                co."CO-NETZ-WLAN-C" AS vlan
            FROM
                campusonline.wlan_pwd co
            WHERE
                LOWER(co."CO-NETZ-ENABLED-B") = 'true'
            """,
            """
            DROP VIEW "networktoken"."internal";
            """,
        ),
    ]

    dependencies = [
        ("networktoken", "0002_token_purpose"),
        ("campusonline", "0070_wlan"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
