# Generated by Django 2.2.28 on 2023-02-02 09:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networktoken", "0003_networktoken_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=256)),
                ("password", models.CharField(default="", max_length=256)),
                ("response", models.CharField(default="", max_length=256)),
                ("created", models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="token",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterField(
            model_name="token",
            name="lifetime",
            field=models.DurationField(
                default=datetime.timedelta(seconds=21600),
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(days=1)
                    ),
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=3600)
                    ),
                ],
            ),
        ),
    ]
